# Site settings
title: MYANMAR SPORT SERVICE
email: ego.itunes@dicloud.com
description: ># ျမန္မာနုိင္ငံသားမ်ားအတြက္ Internet တြင္ ေဘာလုံးအားကစားေဆာ့ကစားျခင္းအား ေစ်းနႈန္းခ်ိဳသာစြာျဖင့္ ဝန္ေဆာင္မႈေပးျခင္း 
    ျဖစ္ပါတယ္။ နုိင္ငံတကာနည္းတူ အင္တာနက္တြင္ သင့္စိတ္ျကိဳက္အသင္းကုိ ေငြက်ပ္ ၁၀၀၀ မွ စတင္ကစားနုိင္သည့္ အခြင့္အေရးကုိ ခက္လြတ္မခံဖုိ႔
   M Sport ျဖင့္ လက္တြဲပါ။
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
facebook_username: egobrightan
twitter_username:  ego_1986

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Facebook
    link: www.facebook.com/myanmarsport
  option2:
    name: Official Site
    link: http://mmsportservice.com
  option3:
    name: Guide
    link: http://guide.mmsportservice.com

# Build settings
markdown: kramdown
